--- #YAML:1.0
name:               POE-Component-Client-Stomp-Utils
version:            0.02
abstract:           A set of utility routines for POE clients
author:
    - Kevin L. Esteb <kesteb@wsipc.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Net::Stomp:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
